name: sophia_smallrna
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pysam
  - samtools
  - bedtools
  - bcftools
  - mosdepth
  - bwa
  - jupyterlab
  - ipykernel